import type { IconNode } from 'morphicons/react';
import {
  Plus,
  Link,
  MousePointerClick,
  BarChart2,
  BarChart3,
  ArrowLeft,
  ArrowRight,
  Check,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  X,
  Copy,
  Moon,
  LayoutDashboard,
  Trash2,
  Download,
  Pencil,
  AlertCircle,
  Folder,
  FolderX,
  Trees,
  Info,
  Archive,
  ArchiveRestore,
  Sun,
  Link2Off,
  KeyRound,
  MailCheck,
  Mail,
  Mouse,
  Key,
  User,
  Globe,
  Search,
  SearchX,
  Shield,
  Send,
  Settings,
  SlidersHorizontal,
  RefreshCw,
  CheckSquare,
  ShieldCheck,
  Eye,
  EyeOff,
  AlertTriangle,
  Calendar,
  Clock,
  LogOut,
  Laptop,
  Monitor,
  Smartphone,
  Tablet,
  Bot,
  Loader2,
  ToggleLeft,
  ToggleRight,
  Sparkles,
  Wand2,
  CircleHelp,
  Maximize2,
  Minimize2,
  Wifi,
  WifiOff,
  CloudOff
} from 'lucide';

export const ICON_MAP: Record<string, IconNode> = {
  // Window & Sizing
  fullscreen: Maximize2,
  maximize: Maximize2,
  fullscreen_exit: Minimize2,
  minimize: Minimize2,

  // Actions & Controls
  add: Plus,
  plus: Plus,
  close: X,
  x: X,
  check: Check,
  check_circle: CheckCircle2,
  content_copy: Copy,
  copy: Copy,
  download: Download,
  edit: Pencil,
  pencil: Pencil,
  magic_button: Sparkles,
  magic: Sparkles,
  sparkles: Sparkles,
  auto_awesome: Sparkles,
  wand: Wand2,
  delete: Trash2,
  delete_forever: Trash2,
  trash: Trash2,
  search: Search,
  search_off: SearchX,
  sync: RefreshCw,
  refresh: RefreshCw,
  send: Send,
  toggle_on: ToggleRight,
  toggle_off: ToggleLeft,

  // Navigation & Direction
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  chevron_down: ChevronDown,
  chevron_up: ChevronUp,

  // Folders & Archives
  folder: Folder,
  folder_off: FolderX,
  inventory_2: Archive,
  archive: Archive,
  unarchive: ArchiveRestore,

  // Theme & Appearance
  light_mode: Sun,
  sun: Sun,
  dark_mode: Moon,
  moon: Moon,

  // Visibility
  visibility: Eye,
  eye: Eye,
  visibility_off: EyeOff,
  eye_off: EyeOff,

  // Security & Auth
  lock_reset: KeyRound,
  password: Key,
  key: Key,
  security: Shield,
  shield: Shield,
  verified_user: ShieldCheck,
  person: User,
  user: User,
  logout: LogOut,
  log_out: LogOut,

  // Analytics & Dashboard
  dashboard: LayoutDashboard,
  grid_view: LayoutDashboard,
  analytics: BarChart2,
  equalizer: BarChart2,
  leaderboard: BarChart3,
  ads_click: MousePointerClick,
  mouse: Mouse,
  public: Globe,
  globe: Globe,
  language: Globe,

  // Links
  link: Link,
  add_link: Link,
  link_off: Link2Off,

  // Alerts & Status
  error: AlertCircle,
  warning: AlertTriangle,
  info: Info,
  task_alt: CheckSquare,
  mark_email_read: MailCheck,
  mail: Mail,
  email: Mail,
  forest: Trees,

  // Date & Time
  calendar_today: Calendar,
  calendar: Calendar,
  schedule: Clock,
  clock: Clock,
  tune: SlidersHorizontal,
  settings: Settings,

  // Network & Connectivity
  wifi: Wifi,
  wifi_off: WifiOff,
  offline: WifiOff,
  cloud_off: CloudOff,
  no_internet: WifiOff,
  network_check: Wifi,

  // Devices & Loading
  desktop: Monitor,
  desktop_windows: Monitor,
  monitor: Monitor,
  computer: Monitor,
  laptop: Laptop,
  laptop_mac: Laptop,
  mobile: Smartphone,
  smartphone: Smartphone,
  phone: Smartphone,
  tablet: Tablet,
  tablet_mac: Tablet,
  bot: Bot,
  smart_toy: Bot,
  robot: Bot,
  progress_activity: Loader2,
  loader: Loader2,
  help: CircleHelp
};

export function resolveIconNode(nameOrNode?: string | IconNode): IconNode {
  if (!nameOrNode) return CircleHelp;
  if (typeof nameOrNode !== 'string') return nameOrNode;
  const normalized = nameOrNode.toLowerCase().trim();
  return ICON_MAP[normalized] || CircleHelp;
}
